replicaCount: 1

image:
  repository: i2btech-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: i2btech.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

auth:
  enabled: true
  username: admin
  password: admin123

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "manual"
  hostPath: "/data/app-logs"
